k8s_yaml(['kubernetes.yaml'])

k8s_resource('enhance', port_forwards='8080')

local_resource('update', "sed -re 's/time.Unix\(0, ([0-9]*)\)/time.Unix\(0, '\"$(($(date +%s%N)))\"'\)/' -i main.go", deps=['update'])

local_resource('recompiler', 'CGO_ENABLED=0 go build -o bigbinary; upx bigbinary -1; mv bigbinary binary', 'main.go', ignore=['binary'])

docker_build('enhance', '.', only=['binary', 'index.html', './diskv', 'start.sh', 'restart.sh'], live_update=[sync('binary', '/app/'), run('./restart.sh')])
